export { default as Discord } from './Discord.vue'
export { default as Github } from './Github.vue'
export { default as Instagram } from './Instagram.vue'
export { default as Linkedin } from './Linkedin.vue'
export { default as X } from './X.vue'
export { default as Youtube } from './Youtube.vue'
